stable-patches: Update 4.9.125 generic-commands as POC
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/4.9.125/generic-commands b/4.9.125/generic-commands
--- a/4.9.125/generic-commands
+++ b/4.9.125/generic-commands
@@ -11,29 +11,58 @@ function header() {
     echo -e "\033[0m"
 }
 
-header "Resetting all conflicts"
-git cf
-echo
-git rm drivers/staging/android/ion/ion-ioctl.c
-git rm fs/squashfs/file_cache.c
-git rf "arch/arm64/mm/init.c drivers/staging/android/ion/ion.c drivers/staging/android/ion/ion_priv.h fs/squashfs/file.c fs/squashfs/file_direct.c fs/squashfs/squashfs.h"
-[[ -n ${FLASH} && "$(basename "${PWD}")" = "op6" ]] && git rf "fs/fuse/dev.c"
+APPROVED_CONFLICTS=( "arch/arm64/mm/init.c"
+                     "drivers/staging/android/ion/ion.c"
+                     "drivers/staging/android/ion/ion-ioctl.c:rm"
+                     "drivers/staging/android/ion/ion_priv.h"
+                     "fs/squashfs/file.c"
+                     "fs/squashfs/file_cache.c:rm"
+                     "fs/squashfs/file_direct.c"
+                     "fs/squashfs/squashfs.h" )
+[[ -n ${FLASH} && "$(basename "${PWD}")" = "op6" ]] && APPROVED_CONFLICTS+=( "fs/fuse/dev.c" )
+readarray -t CONFLICTS <<< "$(git cf)"
+if [[ -n "${CONFLICTS[*]}" ]]; then
+    header "Resetting all conflicts"
+    for CONFLICT in "${CONFLICTS[@]}"; do
+        FOUND=false
+        for APPROVED_CONFLICT in "${APPROVED_CONFLICTS[@]}"; do
+            ACTION=${APPROVED_CONFLICT##*:}
+            APPROVED_CONFLICT=${APPROVED_CONFLICT%%:*}
+            [[ ${ACTION} = ${APPROVED_CONFLICT} ]] && ACTION=rf
+            [[ ${CONFLICT} = ${APPROVED_CONFLICT} ]] && { FOUND=true; break; }
+        done
+        if ${FOUND}; then
+            case ${ACTION} in
+                "rf") ACTION_STRING="Resetting" ;;
+                "rm") ACTION_STRING="Removing" ;;
+                *) echo "Invalid action: ${ACTION}"; exit 1 ;;
+            esac
 
-header "Applying all patches"
-git fp -1 --stdout 91d8631417bdfbee010fd0be4b19dee7cecaeb43 | git ap -R || exit 1
-git fp -1 --stdout 5ad356eabc47d26a92140a0c4b20eba471c10de3 | git ap || exit 1
-if [[ -n ${FlASH} ]]; then
-    git fp -1 --stdout a2477b0e67c52f4364a47c3ad70902bc2a61bd4c | git ap || exit 1
-fi
-git ap "${PATCHES_FOLDER}"/*.diff || exit 1
-if [[ -n ${FLASH} && "$(basename "${PWD}")" = "op6" ]]; then
-    for SHA in 87114373ea50 45ff350bbd9d b8f95e5d13f5 a2477b0e67c5; do
-        git fp -1 --stdout ${SHA} | git ap --include fs/fuse/dev.c || exit 1
+            echo "${ACTION_STRING} ${CONFLICT}..."
+            git "${ACTION}" "${CONFLICT}" &>/dev/null
+        else
+            echo "${CONFLICT} not accounted for, bailing out!"
+            exit 1
+        fi
     done
-fi
+    [[ -n "$(git cf)" ]] && { echo -n "\nResetting conflicts failed!"; exit 1; }
 
-header "Committing merge"
-git fm || exit 1
+    header "Applying all patches"
+    git fp -1 --stdout 91d8631417bdfbee010fd0be4b19dee7cecaeb43 | git ap -R || exit 1
+    git fp -1 --stdout 5ad356eabc47d26a92140a0c4b20eba471c10de3 | git ap || exit 1
+    if [[ -n ${FlASH} ]]; then
+        git fp -1 --stdout a2477b0e67c52f4364a47c3ad70902bc2a61bd4c | git ap || exit 1
+    fi
+    git ap "${PATCHES_FOLDER}"/*.diff || exit 1
+    if [[ -n ${FLASH} && "$(basename "${PWD}")" = "op6" ]]; then
+        for SHA in 87114373ea50 45ff350bbd9d b8f95e5d13f5 a2477b0e67c5; do
+            git fp -1 --stdout ${SHA} | git ap --include fs/fuse/dev.c || exit 1
+        done
+    fi
+
+    header "Committing merge"
+    git fm || exit 1
+fi
 
 header "Applying additional commits"
 rm -f *.patch
