stable-patches: 4.4.157: Update for new generic-commands format
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

diff --git a/4.4.157/generic-commands b/4.4.157/generic-commands
--- a/4.4.157/generic-commands
+++ b/4.4.157/generic-commands
@@ -11,37 +11,45 @@ function header() {
     echo -e "\033[0m"
 }
 
-APPROVED_CONFLICTS=( "block/blk-cgroup.c"
-                     "kernel/locking/rwsem-xadd.c" )
+function die() {
+    echo -e "\033[01;31m"
+    echo "${@}"
+    echo -e "\033[0m"
+    exit 1
+}
+
+APPROVED_CONFLICTS=( "block/blk-cgroup.c:1"
+                     "kernel/locking/rwsem-xadd.c:1" )
 readarray -t CONFLICTS <<< "$(git cf)"
 if [[ -n "${CONFLICTS[*]}" ]]; then
     header "Resetting all conflicts"
     for CONFLICT in "${CONFLICTS[@]}"; do
         FOUND=false
         for APPROVED_CONFLICT in "${APPROVED_CONFLICTS[@]}"; do
-            ACTION=${APPROVED_CONFLICT##*:}
-            APPROVED_CONFLICT=${APPROVED_CONFLICT%%:*}
-            [[ ${ACTION} = ${APPROVED_CONFLICT} ]] && ACTION=rf
+            ACTION=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 3)
+            NOC=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 2)
+            APPROVED_CONFLICT=$(echo "${APPROVED_CONFLICT}" | cut -d : -f 1)
+            [[ -z ${ACTION} ]] && ACTION=rf
             [[ ${CONFLICT} = ${APPROVED_CONFLICT} ]] && { FOUND=true; break; }
         done
+        [[ ${NOC} -ne $(git lo HEAD..MERGE_HEAD "${CONFLICT}" | wc -l) ]] && die "${CONFLICT} resolution might be outdated!"
         if ${FOUND}; then
             case ${ACTION} in
                 "rf") ACTION_STRING="Resetting" ;;
                 "rm"*) ACTION_STRING="Removing" ;;
-                *) echo "Invalid action: ${ACTION}"; exit 1 ;;
+                *) die "Invalid action: ${ACTION}" ;;
             esac
 
             echo "${ACTION_STRING} ${CONFLICT}..."
             git "${ACTION}" "${CONFLICT}" &>/dev/null
         else
-            echo "${CONFLICT} not accounted for, bailing out!"
-            exit 1
+            die "${CONFLICT} not accounted for, bailing out!"
         fi
     done
-    [[ -n "$(git cf)" ]] && { echo -n "\nResetting conflicts failed!"; exit 1; }
+    [[ -n "$(git cf)" ]] && die "Resetting conflicts failed!"
 
     header "Applying all patches"
-    git ap "${PATCHES_FOLDER}"/"$(basename "${APPROVED_CONFLICTS[0]}")".diff || exit 1
+    git ap "${PATCHES_FOLDER}"/"$(basename "${APPROVED_CONFLICTS[0]%%:*}")".diff || exit 1
     echo "Checking out kernel/locking/rwsem-xadd.c..."
     git ch MERGE_HEAD -- kernel/locking/rwsem-xadd.c
 
